---
- name: copy flannel rpm
  copy:
    src: flannel-0.5.1-2.el7.x86_64.rpm
    dest: /tmp/flannel-0.5.1-2.el7.x86_64.rpm

- name: install flannel
  yum:
    name: /tmp/flannel-0.5.1-2.el7.x86_64.rpm
    state: present
  become: true

- name: generate flannel config
  template:
    src: flannel-config.json.j2
    dest: /tmp/flannel-config.json
  when:
    kind == "master"

    



